Makefile: add missing byteorder.h dependency on object files
Noticed missing target directory dependency as a build failure in
`make --shuffle` mode (added in https://savannah.gnu.org/bugs/index.php?62100):

    gcc -O2 -DCOLOR -O -std=c99   -c -o readfile.o readfile.c
    readfile.c:32:10: fatal error: byteorder.h: No such file or directory
       32 | #include "byteorder.h"
          |          ^~~~~~~~~~~~~

The change adds generated header depenendy for all object files to
avoid precise dependency tracking for individual sources or headers
that could include autogenerated file.